---
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
  build:
    commands:
      - docker build --tag "$IMAGE_URI" ./
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - printf '[{"name":"satosa","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  discard-paths: yes
  files:
    - .cloudformation/service.yaml
    - images.json
