---
version: 0.2
phases:
  install:
    commands:
      - curl --location https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 > /usr/local/bin/jq && chmod 0755 /usr/local/bin/jq
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
  build:
    commands:
      - docker build --tag "$IMAGE_URI" ./
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - jq -c -S -n -f .awscodepipeline/config.json.template > .awscodepipeline/config.json
artifacts:
  discard-paths: yes
  files:
    - .cloudformation/service.yaml
    - .awscodepipeline/config.json
